### ISSUE TITLE
Clean up imported WP content

### ISSUE THREAD

**Issue by egardner** [gettypubs/beyond-the-printed-page#3]
@geealbers @sgrimes12 

Here's an issue for the content changes that would be helpful.
In the YAML frontmatter for `_posts`, there is a lot of extra data from Wordpress that is no longer necessary.

All current `tags` can be merged with `categories`.
Things that can be removed:

``` yaml
# Date info is no longer necessary and can go
date: 2013-03-11 09:58:14.000000000 -07:00 

# Type: post is also unnecessary now
type: post

# Anything in the "meta" block can go:
meta:
  _cc_post_template_type: img-left-content-right
  _edit_last: '3'
  _cc_post_template_on: ''
  _cc_post_template_tags: ''
  _cc_post_template_comments_info: ''
  _cc_post_template_date: ''
  _cc_post_template_avatar: ''

# For authors we just need author: name
# so this:
author:
  login: leahtriplett
  email: triplett.leah@gmail.com
  display_name: Leah Triplett
  first_name: Leah
  last_name: Triplett

# can be reduced to:
author: Leah Triplett
```
